import React, { useMemo, useState } from 'react';
import { Search, Github, ShieldCheck, UserMinus, UserCog, FolderKanban, GitCommitHorizontal, Megaphone, Copy, Check, ExternalLink } from 'lucide-react';
import { ClubMemberItem, ClubProjectItem, UserRole } from '../types/store';

export interface ActivityItem { id:string; type:string; title:string; detail:string; actor:string; time:string; }
export interface AnnouncementItem { id:string; title:string; message:string; author:string; publishedAt:string; category:string; }

const sourceCommittee = [
  ['Faculty Coordinators','Khara Solanki • Shrusti Gajjar • Brinda Patel'],
  ['Convener','Amit Thakkar'],
  ['Technical Team Leads','Ohm Bhatia • Priyesh Bhalodiya'],
  ['Technical Team','Nisarg Makwana • Erva Savaliya'],
  ['Management Team Leads','Om Rashiya • Dhruv Kava'],
  ['Management Team','Mendpara Shubham • Kirtan Kakadiya'],
  ['Social Media Managers','Bhargav Rathod • Mayank Parmar'],
] as const;

export function MembersView({ members, currentRole, onChangeRole, onRemove }: { members: ClubMemberItem[]; currentRole: UserRole; onChangeRole:(id:string, role:UserRole)=>void; onRemove:(id:string)=>void }) {
  const [q,setQ]=useState(''); const [domain,setDomain]=useState('all');
  const domains=Array.from(new Set(members.map(m=>m.domain)));
  const rows=useMemo(()=>members.filter(m=>(m.name+' '+m.email+' '+m.githubHandle).toLowerCase().includes(q.toLowerCase())&&(domain==='all'||m.domain===domain)),[members,q,domain]);
  return <div className="space-y-5">
    <div className="flex flex-col md:flex-row md:items-end justify-between gap-3"><div><p className="text-[11px] font-mono uppercase tracking-[.16em] text-purple-600">Roster</p><h1 className="text-2xl font-black text-slate-900">Committee & members</h1><p className="text-sm text-slate-500 mt-1">Search, inspect domains and manage roles from one roster.</p></div><div className="flex gap-2"><div className="relative"><Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search members" className="w-56 pl-9 pr-3 py-2.5 rounded-xl border border-slate-200 bg-white/85 text-xs outline-none focus:border-purple-400"/></div><select value={domain} onChange={e=>setDomain(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 text-xs font-semibold"><option value="all">All domains</option>{domains.map(d=><option key={d}>{d}</option>)}</select></div></div>
    <section className="github-surface rounded-2xl p-5">
      <div className="flex items-center justify-between gap-3 mb-4"><div><div className="text-[11px] font-mono uppercase tracking-wider text-purple-600">Source-provided committee</div><h2 className="font-black text-base">GrowWithGit team structure</h2></div><span className="text-[11px] text-slate-400">Provided club material</span></div>
      <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{sourceCommittee.map(([role,names])=><div key={role} className="p-3 rounded-xl bg-slate-50/80 border border-slate-100"><div className="text-[11px] font-bold uppercase tracking-wider text-slate-400">{role}</div><div className="text-xs font-semibold text-slate-800 mt-1 leading-relaxed">{names}</div></div>)}</div>
    </section>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['Members',members.length],['Core team',members.filter(m=>m.isCore).length],['GitHub handles',members.filter(m=>m.githubHandle).length],['Active roles',new Set(members.map(m=>m.role)).size]].map(([l,v])=><div key={l as string} className="github-surface rounded-2xl p-4"><div className="text-[11px] uppercase tracking-wider text-slate-400 font-bold">{l}</div><div className="text-2xl font-black mt-1">{v}</div></div>)}</div>
    <div className="github-surface rounded-2xl overflow-hidden"><div className="hidden md:grid grid-cols-[1.6fr_1fr_1fr_1fr_1fr_auto] gap-3 px-5 py-3 border-b border-slate-100 text-[11px] uppercase tracking-wider font-bold text-slate-400"> <span>Member</span><span>Year / branch</span><span>Domain</span><span>Role</span><span>GitHub</span><span>Actions</span></div>{rows.slice(0,80).map(m=><div key={m.id} className="grid grid-cols-1 md:grid-cols-[1.6fr_1fr_1fr_1fr_1fr_auto] gap-2 md:gap-3 px-5 py-3.5 border-b border-slate-100/80 last:border-0 items-center hover:bg-slate-50/70"><div><div className="font-bold text-sm text-slate-900">{m.name} {m.isCore&&<span className="ml-1 text-[11px] px-1.5 py-0.5 rounded-full bg-purple-50 text-purple-700 border border-purple-200">CORE</span>}</div><div className="text-[11px] text-slate-400">{m.email}</div></div><div className="text-xs text-slate-600">{m.yearOrdinal}<br/>{m.branch}</div><div className="text-xs font-medium text-purple-700">{m.domain}</div><div><select disabled={currentRole!=='admin'} value={m.role} onChange={e=>onChangeRole(m.id,e.target.value as UserRole)} className="text-[11px] rounded-lg border border-slate-200 px-2 py-1.5 bg-white disabled:opacity-60"><option value="admin">Admin</option><option value="event_lead">Event Lead</option><option value="member">Member</option></select></div><a href={`https://github.com/${m.githubHandle}`} target="_blank" rel="noreferrer" className="text-xs font-mono text-slate-600 hover:text-[#f05032] flex items-center gap-1">@{m.githubHandle}<ExternalLink className="w-3 h-3"/></a><div>{currentRole==='admin'&&!m.isCore&&<button onClick={()=>onRemove(m.id)} className="p-2 rounded-lg text-slate-400 hover:text-rose-600 hover:bg-rose-50" title="Remove member"><UserMinus className="w-3.5 h-3.5"/></button>}</div></div>)}{rows.length===0&&<div className="p-10 text-center text-sm text-slate-500">No members match this filter.</div>}</div>
  </div>;
}

export function ProjectsView({ projects, members, activeMemberId, currentRole, onRequestJoin }: { projects: ClubProjectItem[]; members:ClubMemberItem[]; activeMemberId:string; currentRole:UserRole; onRequestJoin:(id:string)=>void }) {
  return <div className="space-y-5"><div><p className="text-[11px] font-mono uppercase tracking-[.16em] text-purple-600">Workspaces</p><h1 className="text-2xl font-black">Projects & activity</h1><p className="text-sm text-slate-500 mt-1">A compact view of what the club is building and where help is needed.</p></div><div className="grid md:grid-cols-2 gap-4">{projects.map(p=>{const lead=members.find(m=>m.id===p.leadMemberId); const pct=Math.round((p.contributorIds.length/Math.max(p.maxContributors,1))*100); const canJoin=currentRole==='member'&&p.status!=='Completed'&&!p.contributorIds.includes(activeMemberId)&&!p.pendingApplicantIds.includes(activeMemberId); return <div key={p.id} className="github-surface card-hover rounded-2xl p-5 space-y-4"><div className="flex items-start justify-between gap-3"><div><span className="text-[11px] font-bold uppercase tracking-wider text-purple-600">{p.category}</span><h3 className="font-black text-lg mt-1">{p.title}</h3></div><span className={`text-[11px] px-2 py-1 rounded-full font-bold ${p.status==='Active'?'bg-emerald-50 text-emerald-700':p.status==='Completed'?'bg-slate-100 text-slate-600':'bg-amber-50 text-amber-700'}`}>{p.status}</span></div><p className="text-xs text-slate-600 leading-relaxed">{p.description}</p><div><div className="flex justify-between text-[11px] text-slate-400 mb-1"><span>Contributor capacity</span><span>{p.contributorIds.length}/{p.maxContributors}</span></div><div className="h-2 rounded-full bg-slate-100 overflow-hidden"><div className="h-full bg-gradient-to-r from-purple-500 to-[#f05032] rounded-full" style={{width:`${Math.min(100,pct)}%`}}/></div></div><div className="flex items-center justify-between text-[11px]"><span className="text-slate-500">Lead: <strong className="text-slate-800">{lead?.name||'Committee'}</strong></span>{canJoin?<button onClick={()=>onRequestJoin(p.id)} className="px-3 py-1.5 rounded-lg bg-slate-900 text-white font-bold hover:bg-purple-700">Request to join</button>:<span className="text-slate-400">{p.contributorIds.length} contributors</span>}</div></div>})}</div></div>;
}

export function ActivityView({ items }: { items: ActivityItem[] }) { return <div className="space-y-5"><div><p className="text-[11px] font-mono uppercase tracking-[.16em] text-purple-600">Commit feed</p><h1 className="text-2xl font-black">Recent activity</h1><p className="text-sm text-slate-500 mt-1">Every important dashboard mutation is reflected here.</p></div><div className="github-surface rounded-2xl divide-y divide-slate-100">{items.map(a=><div key={a.id} className="p-5 flex gap-4"><div className="w-9 h-9 rounded-xl bg-purple-50 text-purple-700 flex items-center justify-center shrink-0"><GitCommitHorizontal className="w-4 h-4"/></div><div className="min-w-0"><div className="font-bold text-sm">{a.title}</div><div className="text-xs text-slate-500 mt-0.5">{a.detail}</div><div className="text-[11px] font-mono text-slate-400 mt-2">{a.actor} · {a.time} · {a.type}</div></div></div>)}{!items.length&&<div className="p-10 text-center text-sm text-slate-500">No activity yet.</div>}</div></div> }

export function AnnouncementsView({ items }: { items: AnnouncementItem[] }) { const [copied,setCopied]=useState<string|null>(null); const copy=async(a:AnnouncementItem)=>{await navigator.clipboard?.writeText(`${a.title}\n\n${a.message}`);setCopied(a.id);setTimeout(()=>setCopied(null),1200)}; return <div className="space-y-5"><div><p className="text-[11px] font-mono uppercase tracking-[.16em] text-purple-600">Broadcasts</p><h1 className="text-2xl font-black">Announcements</h1><p className="text-sm text-slate-500 mt-1">Publish-ready updates for members and social channels.</p></div><div className="grid md:grid-cols-2 gap-4">{items.map(a=><article key={a.id} className="github-surface rounded-2xl p-5"><div className="flex items-center justify-between"><span className="text-[11px] uppercase font-bold tracking-wider text-[#f05032]">{a.category}</span><button onClick={()=>copy(a)} className="text-[11px] font-semibold text-slate-500 hover:text-slate-900 flex items-center gap-1.5">{copied===a.id?<Check className="w-3.5 h-3.5 text-emerald-600"/>:<Copy className="w-3.5 h-3.5"/>}{copied===a.id?'Copied':'Copy'}</button></div><h3 className="font-black text-lg mt-2">{a.title}</h3><p className="text-xs text-slate-600 leading-relaxed mt-2">{a.message}</p><div className="text-[11px] text-slate-400 mt-4">{a.author} · {a.publishedAt}</div></article>)}</div></div> }
